Migrate the qemu supervisor (and adjacent components) to tracing
treadmill-tb/treadmill pull request #44
Opened 2024-08-13 14:35 UTC by lschuermann

This allows us to debug why the QEMU supervisor fails to start, without looking at the state changes that are pushed to the switchboard.

I'm sure that we'll want to fine-tune the `#[instrument` scopes later on, but this seems to give a decent amount of debug information while not printing out types that would be too large to display in the context of every message.

2024-08-13 14:40 UTC, lschuermann commented on switchboard/cli/Cargo.toml
> -path = "../switchboard"
This change is not related, but we were pulling in a bunch of other dependencies into the CLI through this false dependency on the switchboard. Things work file with this removed.

2024-08-13 14:48 UTC, lschuermann commented on switchboard/cli/Cargo.toml
> -path = "../switchboard"
Split out into #45.

2024-08-13 21:57 UTC, max-cura approved these changes

2024-08-13 22:06 UTC, max-cura requested changes
Need to regenerate Cargo.lock.

2024-08-15 17:43 UTC, max-cura approved these changes
LGTM.

2024-08-16 00:09 UTC, merged